github: [theabbie]
patreon: theabbie
open_collective: theabbie
ko_fi: theabbie
tidelift: npm/theabbie
liberapay: theabbie
issuehunt: theabbie
otechie: theabbie
custom: ['https://theabbie.github.io', 'https://iferr.now.sh']
